version: '3.9'

services:
  src:
    container_name: qitpy_src_release
    depends_on:
      - database
    build:
      context: .
      args:
        - PORT_EXPOSE=${API_SERVICE_PORT}
    restart: unless-stopped
    volumes:
      - qitpy-static-data:/vol/web
    environment:
      - API_SERVICE_PORT=${API_SERVICE_PORT}
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    expose:
      - ${API_SERVICE_PORT}
    networks:
      - qitpy-server
      - qitpy-proxy_qitpy-proxy

  pgadmin:
    container_name: qitpy_pgadmin_release
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    volumes:
      - qitpy-pgadmin:/var/lib/pgadminz
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    networks:
      - qitpy-server
      - qitpy-proxy_qitpy-proxy

  database:
    container_name: qitpy_database_release
    image: postgres:13-alpine
    volumes:
      - qitpy-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - qitpy-server

volumes:
  qitpy-db:
  qitpy-pgadmin:
  qitpy-static-data:
networks:
  qitpy-server:
    driver: bridge
  qitpy-proxy_qitpy-proxy:
    external: true