version: '3.9'

services:
  src:
    container_name: maito_src_dev
    depends_on:
      - database
    build:
      context: .
      args:
        - DEV=true
        - PORT_EXPOSE=${API_LOCAL_PORT}
    ports:
      - ${API_LOCAL_PORT}:${API_LOCAL_PORT}
    volumes:
      - ./src:/src
      - maito-static-data-dev:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${API_LOCAL_PORT}"
    environment:
      - DEBUG=1
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - API_LOCAL_PORT=${API_LOCAL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

  pgadmin:
    container_name: maito_pgadmin_dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - maito-pgadmin-dev:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    restart: unless-stopped

  database:
    container_name: maito_database_dev
    image: postgres:13-alpine
    volumes:
      - maito-db-data-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  maito-db-data-dev:
  maito-pgadmin-dev:
  maito-static-data-dev: