# Generated by Django 4.1.3 on 2022-11-17 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TodoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('HT', 'HIGHEST'), ('H', 'HIGH'), ('L', 'LOW'), ('LT', 'LOWEST')], max_length=2, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoMonthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todocard')),
            ],
        ),
        migrations.CreateModel(
            name='TodoScheduleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_time', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.todocard')),
            ],
        ),
        migrations.CreateModel(
            name='TodoYearCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('month_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todomonthcard')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todocard')),
            ],
        ),
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_note', models.TextField(blank=True, default='there are no note', null=True)),
                ('daily_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='core.todocard')),
                ('schedule_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todoschedulecard')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todocard')),
                ('tasks_months', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todomonthcard')),
                ('tasks_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todoyearcard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
