# Generated by Django 4.1.3 on 2022-11-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolioaccessfrequency_portfoliomessage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfolioaccessfrequency',
            table='portfolio_access_frequency',
        ),
    ]
