# Generated by Django 4.1.3 on 2022-11-24 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usertodo_daily_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodo',
            name='schedule_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.todoschedule'),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.todocard'),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='tasks_months',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.todomonth'),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='tasks_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.todoyear'),
        ),
    ]
