# Generated by Django 4.1.3 on 2022-11-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usertodo_schedule_tasks_alter_usertodo_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertodo',
            name='daily_tasks',
        ),
        migrations.RemoveField(
            model_name='usertodo',
            name='schedule_tasks',
        ),
        migrations.RemoveField(
            model_name='usertodo',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='usertodo',
            name='tasks_months',
        ),
        migrations.RemoveField(
            model_name='usertodo',
            name='tasks_year',
        ),
    ]
