# Generated by Django 4.1.3 on 2022-11-24 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_todocard_user_todo_todomonth_user_todo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomonth',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='todoschedule',
            name='task',
        ),
        migrations.RemoveField(
            model_name='todoyear',
            name='month_tasks',
        ),
        migrations.RemoveField(
            model_name='todoyear',
            name='tasks',
        ),
        migrations.AddField(
            model_name='todomonth',
            name='child_task',
            field=models.ManyToManyField(to='core.todocard'),
        ),
        migrations.AddField(
            model_name='todomonth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 24, 11, 35, 0, 676874, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomonth',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todomonth',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todomonth',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todomonth',
            name='month_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomonth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todoschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 24, 11, 35, 0, 676874, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoschedule',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoschedule',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoschedule',
            name='name',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todoyear',
            name='child_task',
            field=models.ManyToManyField(to='core.todocard'),
        ),
        migrations.AddField(
            model_name='todoyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 24, 11, 35, 44, 261689, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoyear',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoyear',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoyear',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoyear',
            name='month_todo',
            field=models.ManyToManyField(to='core.todomonth'),
        ),
        migrations.AddField(
            model_name='todoyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='todocard',
            table='todo_cards',
        ),
        migrations.CreateModel(
            name='TodoDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('user_todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usertodo')),
            ],
            options={
                'db_table': 'todo_daily',
            },
        ),
    ]
