name: maito-server

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker-compose -f docker-compose-deploy.yml build
      - name: Test checking
        run: docker-compose -f docker-compose-deploy.yml run --rm src sh -c "coverage run manage.py test"
      - name: Report checking
        run: docker-compose -f docker-compose-deploy.yml run --rm src sh -c "coverage report"
      - name: Flake8 checking
        run: docker-compose -f docker-compose-deploy.yml run --rm src sh -c "flake8 --exclude=core/migrations/"
      - name: run
        run: docker-compose up -d
