name: maito-server

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker-compose -f docker-compose-deploy.yml build
      - name: Test
        run: docker-compose -f docker-compose-deploy.yml run --rm src -c "coverage run manage.py test"
      - name: Report
        run: docker-compose -f docker-compose-deploy.yml run --rm src -c "coverage report"
      - name: Lint
        run: docker-compose -f docker-compose-deploy.yml run --rm src -c "flake8"
      - name: run
        run: docker-compose up -d
