name: qitpy-server

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: env setting
        run: cp .env.example .env
      - name: test prepare
        run: docker-compose build
      - name: wait for db
        run: docker-compose run --rm src sh -c "python manage.py wait_for_db"
      - name: run test case
        run: docker-compose run --rm src sh -c "python manage.py test"
      - name: run test flake8
        run: docker-compose run --rm src sh -c "flake8 --exclude=core/migrations/,server/settings.py,*/__init__.py,*/*/__init__.py"
  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ENV setting
        run: cp ~/.env .
      - name: Remove images
        run: docker-compose -f docker-compose-deploy.yml down
      - name: Build
        run: docker-compose -f docker-compose-deploy.yml build
      - name: run
        run: docker-compose -f docker-compose-deploy.yml up -d
